### ISSUE TITLE
Before or after body parser when using as middleware?

### ISSUE THREAD

**Issue by dstroot** [ericmdantas/express-content-length-validator#1]
Also how do I get it to pass the error down my middleware stack rather than immediately responding with a JSON response?

**Comment by ericmdantas** [comment]
Hello!

You'd have to use it before the body parser, otherwise the payload would already have been parsed and your app could be in danger.

About the passing down the error to the next middleware, right now you can't do that - but I can create an option for that, if you'd like.

**Comment by ericmdantas** [comment]
Also, I'll doc the middleware order, it's a good point.

**Comment by dstroot** [comment]
Great - cheers!  Also I found that body parser has a limit now built-in.

**Comment by dougwilson** [comment]
>  Also I found that body parser has a limit now built-in.

There was never a time when it wasn't built it ;)

**Comment by dougwilson** [comment]
It doesn't seem like this module accounts for chunked requests, which do not have a `content-length` header, so a 8GB chunked request would still get through just fine.

**Comment by ericmdantas** [comment]
@dougwilson that's true.
