### ISSUE TITLE
Is this needed when using express-js body-parser?

### ISSUE THREAD

**Issue by mrawdon** [ericmdantas/express-content-length-validator#2]
There is a limit field on the express-js body-parser middleware https://github.com/expressjs/body-parser#limit When using that to parse my request body, is there any need to use this library as well?  Or do these both serve the same purpose?

Thanks

**Comment by ericmdantas** [comment]
Hello!

Well, as you said, body-parser already has a "limiter", so you can use that. If you plan to use this middleware together with body-parser, I'd say you put it before the body-parser declaration.
