### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by ddesna** [ericmdantas/express-content-length-validator#4]
With [generator-ng-fullstack](https://github.com/ericmdantas/generator-ng-fullstack) it is configured by default. I've added file uploading with `multer` and had `Invalid payload` error.

In this case how can I use `express-content-length-validator` ?

Thanks.

**Comment by ericmdantas** [comment]
You can either pass a higher value to the `max` prop in the validator function, or, if it makes sense for your app, not use this module.
